### ISSUE TITLE
Compatiility with browser mod tap action fire-dom-event

### ISSUE THREAD

**Issue by BrendanxP** [luixal/lovelace-media-source-image-card#12]
I am not sure if this is something that can easily be implemented, however,  it would be amazing if this card worked smoothly with browser mod. What I am trying to achieve is to get a tap action fire-dom-event working from your lovelace-media-source-image-card. I am running version 3.0 of this frontend integration via HACS.

Lets go straight to an example; When I hit the following button a sounds gets played:
```
type: custom:button-card
name: |
  [[[ return `Pokémon No.${states['sensor.random_pokemon'].state}`; ]]]
tap_action:
  action: fire-dom-event
  browser_mod:
    service: script.play_sound_based_on_number
    data:
      browser_id: THIS
      number: '[[[ return states[''sensor.random_pokemon''].state; ]]]'
```

However, I get an error/warning and no sound playing when I try it with your card, as follows:
```
type: custom:media-source-image-card
image: >-
  media-source://media_source/local/test{{ states('sensor.random_pokemon')
  }}.png
entity_id: sensor.random_pokemon
forced_refresh_interval: 10
tap_action:
  action: fire-dom-event
  browser_mod:
    service: script.play_sound_based_on_number
    data:
      browser_id: THIS
      number: '[[[ return states[''sensor.random_pokemon''].state; ]]]'

```

I get the following error, my best guess is that it defaults to toggle when it sees the unrecognized fire-dom-event.
```
Log details (WARNING)
Logger: homeassistant.components.homeassistant
Source: components/homeassistant/__init__.py:137
integration: Home Assistant Core Integration ([documentation](https://www.home-assistant.io/integrations/homeassistant), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+homeassistant%22))
First occurred: 10:58:44 PM (46 occurrences)
Last logged: 11:29:50 PM

The service homeassistant.toggle does not support entities sensor.random_pokemon
```

If you would like me to perform further testing please let me know!

___ edit ___
Some additional info about the fire-dom-event I am (trying) to perform can be found [here](https://github.com/thomasloven/hass-browser_mod/blob/master/documentation/services.md#a-note-about-targets).
It shows the difference between a browser mod server call and a browser call. And given the "browser" nature of this custom image card, implementing this would fit in very nicely with the card, I would say.

**Comment by luixal** [comment]
Hi,

In this card, the default config sets the default tap action to toggle, that's why you get that error, because `sensor.random_pokemon` can't be toggled. This all happens withing this card, nothing to do with browser mod.

Have you tried settting the `tap_action` to call a service, like in [this example](https://github.com/luixal/lovelace-media-source-image-card#call-service), and then calling a browser_mod service like [browser_mod.sequence](https://github.com/thomasloven/hass-browser_mod/blob/master/documentation/services.md#browser_modsequence) ?

Let me know if that helps, I've really not worked that much with browser mod.

**Comment by luixal** [comment]
I've looking deeper into this and just saw that, when calling a browser mod service from the frontend (lovelace) you don't need to include the browser id to target that browser in particular as that is just the default behaviour:

> Services called via fire-dom-event or called as a part of a different service call will (by default) only target the current Browser (even if it's not registered).

You don't need to pass the random number as a param to your script as the script can get it directly from the sensor (and just seems better to me as it's less verbose and repetitive) so, putting that in the script and just calling the service from the card like this should work:

```yaml
type: custom:media-source-image-card
image: >-
  media-source://media_source/local/test{{ states('sensor.random_pokemon')
  }}.png
entity_id: sensor.random_pokemon
forced_refresh_interval: 10
tap_action:
  action: call-service
  service: script.play_sound_based_on_number
```

Please, just let me know if that works for you :)

**Comment by BrendanxP** [comment]
Thanks a lot for taking the time to check this with me. You are correct about passing the number to the script, I did not do this in the best fashion. However, this issue is really with the browser_id, specifically getting the media_player of the current browser. 

I have tried many ways, but I cannot figure out how to target a media_player.{{browser_id}}, without passing the browser_id via the fire-dom-event. Like the text you quote, it says it will target the current browser automatically. However, when I want to media_player.play on a device, I have to specify the media_player. I cannot just leave it blank for browser mod to find the media_player of the current browser. 
Furthermore, when doing a service call and not a fire-dom-event, {{browser_id}} is undefined. This means I cannot simply make this ID appear as part of the script when doing a regular service call. Hence, why I stuck to using the fire-dom-event. The fire-dom-event like I showed before does work on other cards like I showed in my initial post, but not on your media_source_card. 

I went on to try an easier example where the browser_id would be resolved automatically. 
When I put the following tap action on a regular or custom button card, or picture entity card, it opens the pop-up on all browser instances.
```
tap_action:
  action: call-service
  service: browser_mod.popup
  data:
    title: Lights
    content:
      type: entities
      entities:
        - entity: light.tv_board
          name: TV Board
        - entity: light.hyperhdr
          name: Ambilight
```

When I put this action in your custom media card, I get the following error:
```
Log details (ERROR)
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:301
integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 12:11:14 PM (17 occurrences)
Last logged: 12:40:13 PM

[140278319204800] Error handling message: extra keys not allowed @ data['target']['sequence']. Got [{'service': 'script.play_sound_based_on_number2'}] (invalid_format) Brendan from 172.71.103.135 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0)
```

The next thing I tried is putting the popup service call in a fire-dom-event. When putting this is regular cards, it opens the popup ONLY on the current browser. This shows that indeed the fire-dom-event is what keeps track of the current browser instance and now performs a "browser call", whereas the previous example was a "server call".
```
type: picture
image: https://demo.home-assistant.io/stub_config/t-shirt-promo.png
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Lights
      content:
        type: entities
        entities:
          - entity: light.tv_board
            name: TV Board
          - entity: light.hyperhdr
            name: Ambilight
```

When running this tap action in your custom media card I again get the error about the toggle action not working as the fire-dom-event is not recognized.

I hope this helps your understanding further. I tried to see how the custom button card handles this, but that code is too large and complex for me to pinpoint the solution. Maybe this is something you could figure out if you have the time and want to put in the effort. 

The browser_mod.sequence shows the same behaviour as with the pop-up card. It can capture the current browser_id when launched from a fire-dom-event, but not without it.
