### ISSUE TITLE
Feature Request: Display all images

### ISSUE THREAD

**Issue by nehasjains** [luixal/lovelace-media-source-image-card#19]
```
type: custom:media-source-image-card
image: |
  media-source://media_source/local/{{ '%02d' % range(1, 20) | random }}.png
entity_id: input_boolean.boolean_test
apply_grayscale: true
forced_refresh_interval: 10
tap_action:
  action: call-service
  service: input_boolean.turn_on
  target:
    entity_id: input_boolean.boolean_test
```
The above code display images randomly. But the files have to numbered.

Is there a way to display images in a folder randomly irrespective for their names.?

So e.g. if the folder has 20 images.
      
      ```
      maximum_files: 15
      slideshow_timer: 5
      random_sort: true
```
By adding the parameters, the plugin would display fifteen files in random order as a slideshow.
If maximum_files is not specified the plugin would display all images in the folder specified.

If possible kindly add this. 
Thank you so much. Looking forward to the next update.

**Comment by luixal** [comment]
Hi,

I think that would be a whole different card I think. The functionality you describe is quite bigger that what this card does right now.

I guess you can get something similar by embedding this card in a [button-card](https://github.com/custom-cards/button-card) and using some js code to randomize you filenames (you would have to hardcode all of them).

If you want to show more than one pic, you can use [auto-entities](https://github.com/thomasloven/lovelace-auto-entities) to work that out.

And can combine both to get a more complex solution.

Can you post your config for other users in case you get it working?

**Comment by nehasjains** [comment]
Thank you for your reply and kind suggestions. But I don't know js or any sort of coding. So I have to rely on some addon only.

**Comment by nehasjains** [comment]
This is how I am getting random image from a specified folder.
  1. No matter how many files are there is a folder.
  2. No matter how the files are named.
  

**configuration.yaml**
```
sensor:
  - platform: folder
    folder: /path/to/your/folder/containing_photos
```

**Homeassistant**
```
**Random image using just a template**

type: custom:media-source-image-card
image: |
  media-source://media_source/local/{{ '%02d' % range(1, 20) | random }}.png
entity_id: input_boolean.boolean_test
apply_grayscale: true
forced_refresh_interval: 10
tap_action:
  action: call-service
  service: input_boolean.turn_on
  target:
    entity_id: input_boolean.boolean_test

** The above can be changed like below to get a random image on each refresh from the folder specified**

     type: custom:media-source-image-card
      image: >-
        media-source://media_source/local/{{ state_attr('sensor.containing_photos',
        'file_list') | random | regex_findall('([^/\\\\]+)$') | first }}
        forced_refresh_interval: 10
```
```
This will get only the file name eg. if the image path is /path/to/your/folder/containing_photos/my_image.jpg. The below will return my_image.jpg
{{ state_attr('sensor.containing_photos',
        'file_list') | random | regex_findall('([^/\\\\]+)$') | first }}
```

I hope this would help someone like me who is trying to implement the same.


Thank you again @luixal for the great work.

**Comment by nehasjains** [comment]
```
card_mod:
  style: |
    ha-card {     
      border-color: red !important;
      border-radius: 15px !important;
      background: none !important;
    }
```

Trying to have rounded corners for the card but its not working. Am I doing something wrong here. The same code if used with any other card is working.

**Comment by luixal** [comment]
Hi,

This example is working for rounded corners:

```yaml
card_mod:
  style: |
    ha-card {
      border-radius: 10px 10px 0px 0px !important;
    }
```

have tried yours like this:

```yaml
card_mod:
  style: |
    ha-card {
      border-radius: 10px !important;
    }
```

and also works for me.

Maybe something related to the theme you're using? Can you try with another one?
