### ISSUE TITLE
Feature Request: vertical and horizontal centering

### ISSUE THREAD

**Issue by Kanecaine** [luixal/lovelace-media-source-image-card#20]
Thank you for this card and the new option of being able to set width and height directly. From my point of view, it would be consistent if vertical and horizontal centering were now also possible. I have currently implemented this with card_mod as follows:

```yaml
type: custom:media-source-image-card
image: media-source://media_source/local/IMG_0320.webp
width: 100%
card_mod:
  style: |
    ha-card { 
      display:flex;
      justify-content: center;
      align-items:center;
    }
```

Such centering would be particularly useful for multiple image cards where the embedded images may have different sizes.

Please take a look at it and decide for yourself whether you think it makes sense to include this in the card, possibly also optionally via a yaml switch.

**Comment by luixal** [comment]
Ummm... I guess you need this because you're showing different size images in a row or something like that, are you?

Just saying, because the card itself is applying this css in the content div:

```css
.card-content {
  display: flex;
  align-content: center;
  justify-content: center;
}
```

so the image is already centered by default. ~~This could be moved to the card itself instead the inner div~~ I just removed the `.card-content` inner div and moved this css to the `ha-card` element (v0.5.1).

Can you give more info on what you're trying to achieve? Not sure you need `justify-items` in this card as there's only one single item in it (that's why I'm using `align-content`), but I'm not proficient at all in css.

Thanks!

**Comment by Kanecaine** [comment]
Hey, thanks for your feedback. I'm not a CSS pro either :)

Consider this section in a section layout:

```yaml
type: grid
cards:
  - type: custom:media-source-image-card
    image: media-source://media_source/local/IMG_0320.webp
    card_mod:
      style: |
        ha-card { 
          display:flex;
          justify-content: center;
          align-items:center;
          border: 1px solid red;
        }
    grid_options:
      columns: 5
  - type: custom:media-source-image-card
    image: media-source://media_source/local/IMG_0320.webp
    card_mod:
      style: |
        ha-card { 
          border: 1px solid green;
        }
    grid_options:
      columns: 10
column_span: 2

```

Two times the same image within the same section, one card 5 columns wide and the other 10 columns wide. The section-grid equalizes the heights of the ha-cards. Without further adjustments it looks like this:

<img width="650" alt="Image" src="https://github.com/user-attachments/assets/e455cace-9c9e-4d50-b230-e35b54b49a6c" />

By defining the ha-card as a flexbox with 'vertical-align:center', the image is centered vertically within the ha-card. Possibly 'justify-content: center' for an additional horizontal centering is actually unnecessary, since I could not produce a case where this would have a positive effect (but also no negative effect).

<img width="650" alt="Image" src="https://github.com/user-attachments/assets/c5bae03d-d1dd-4c55-b7ca-8057db72afa7" />

What I'm really wondering about is the border-color that I added to better clarify the borders for the ha-card. The specification in the second card (green) overwrites the specification in the first card (red) - and vice versa, if I define red with “!important”, both are red. This should not be the case, as both specifications exist in separate shadow-roots. I have never observed this before. I can rule out a caching problem, I have observed it on various end devices. I have also deactivated my theme, so this cannot be the cause either. Accordingly, I can't explain this at the moment, but it shouldn't change the situation shown in the images.

--

To further explain my case: In my dashboard, of course, I don't have the same image next to each other twice. This is for illustrative purposes only. I have a vertical-stack-card next to the image, which leads to the same behavior: I want the image to the left of the stack to be vertically centered.
Directly below this section I have another section, again with the image to the left and a vertical-stack-card to the right. I use 'grid_options' of the section to ensure that the image-cards share the same width. Without CSS adjustment, however, they do not appear vertically centered next to the stack.

**Comment by Kanecaine** [comment]
Ok, so with the recent update to 0.5.1 the layout is broken.

<img width="785" alt="Image" src="https://github.com/user-attachments/assets/0151192d-8935-4b10-9ca3-6860296c9824" />

```yaml
type: grid
cards:
  - type: custom:media-source-image-card
    image: media-source://media_source/local/IMG_0621.JPG
    card_mod:
      style: |
        ha-card { 
          /*display:flex;*/
          /*justify-content: center;*/
          /*align-items:center;*/
          border: 2px solid red;
        }
    grid_options:
      columns: 5
  - type: custom:media-source-image-card
    image: media-source://media_source/local/IMG_0621.JPG
    card_mod:
      style: |
        ha-card { 
          border: 1px solid green;
        }
    grid_options:
      columns: 10
column_span: 2
```

The specification of 'height: 100%' should please be removed again from ha-card.

Also, any card_mod style is now not applied at all. In conjunction with the previous observation, I suspect that the media-source-image-card is not implementing the shadow-root correctly. In v0.5.0 this caused inconsistent behavior when card_mod tries to inject the styles. In v0.5.1, however, it no longer works at all (or sometimes sporadically when I am active in the UI editor).
 
~I also noticed the following error in the JS console, which could be related to this:~
<details>
<summary>Seemingly irrelevant error</summary>

content.js:1 Uncaught TypeError: Cannot read properties of null (reading 'shadowRoot')
    at vn (content.js:1:67234)
    at Sr.isValuedField (content.js:1:175310)
    at Cr.onMouseDown (content.js:1:178421)
vn @ content.js:1
Sr.isValuedField @ content.js:1
Cr.onMouseDown @ content.js:1

</details>

~The error appears as soon as I open the UI editor for the media-source-image-card. This is therefore a strong indication that this card could be the cause.~ edit: no, this error also occurs on other cards, so as it seems it does not belong to your card. But it is still strange that card_mod no longer works since the removal of the container-div in 0.5.1 as well as the behavior in the previous version.

Due to the fact that card_mod no longer works at all, I have to go back to the previous version first, as I no longer have any correction options. Please have a look at this.

**Comment by luixal** [comment]
I guess PR #22 fixes this.

**Comment by Kanecaine** [comment]
Unfortunately not. The change in 0.5.2 has the following (even worse) effect:

<img width="785" alt="Image" src="https://github.com/user-attachments/assets/d8c92647-f47e-47a7-a9dc-c6cbfb96df1d" />

```
type: grid
cards:
  - type: custom:media-source-image-card
    image: media-source://media_source/local/IMG_0621.JPG
    grid_options:
      columns: 5
  - type: custom:media-source-image-card
    image: media-source://media_source/local/IMG_0621.JPG
    grid_options:
      columns: 10
column_span: 2
```

In the simplest case, I would like to place 2 images next to each other in a grid section.  In a section view, you can define for each card how many columns it should be wide. This allows relative specifications without absolute pixel specifications. There is only half as much space available for the first card as for the second card. Accordingly, both images cannot be the same size: the first image must be scaled while retaining the aspect ratio. This last worked perfectly with 0.5.0.

0.5.0 --> Images scaled perfectly. Only the left image was not displayed vertically centered next to the right (larger) one. Correction with card_mod was possible.

0.5.1 --> due to “height: 100%” the left image fills the parent container completely, which distorts the image. Correction with card_mod not possible.

0.5.2 --> The image no longer scales at all and overhangs the container. “overflow:hidden” of the container does not work either (but would not be the solution either). Correction with card_mod not possible.

The behavior with 0.5.0 was without problems and whether vertical centering makes sense or not is a matter of taste and could be corrected with card_mod if necessary. Due to the elimination of the container DIV since 0.5.1, card_mod no longer works. I suspect that a div is always expected within ha-card for it to work (which is probably the case with 99.99% of all other cards). 

In addition to solving the scaling problem, I would therefore ask that the img tag within ha-card be enclosed by a div tag again. Even if it has no styles itself, it seems to be needed for correct rendering (at least if card_mod is used).

Thank you for your efforts!

**Comment by luixal** [comment]
I've just tried your config like this:

```yaml
type: grid
cards:
  - type: custom:media-source-image-card
    image: media-source://media_source/local/banana.avif
    grid_options:
      columns: 5
  - type: custom:media-source-image-card
    grid_options:
      columns: 10
    image: media-source://media_source/local/banana.jpeg
column_span: 2
```

and just got this:

![Image](https://github.com/user-attachments/assets/07fe72ba-985e-481f-9305-310a5b15ae24)

Images are not overlapping for me.

Maybe you have some css in your theme? or some css injected from another package?

If you find it useful, I can try to add an `styles` option so you can pass custom css to the `img` element.
