### ISSUE TITLE
Slideshow/folder functionality?

### ISSUE THREAD

**Issue by kennethpangky** [luixal/lovelace-media-source-image-card#25]
With the recent official Immich integration, thought it would be nice if I could display a slideshow of a specific folder from the Immich media source.

**Comment by meldarionqeusse** [comment]
Did you manage to get a single image to show up?  I am having trouble to display a single image from immich media source. I tried the following and nothing shows up

```yml
type: custom:media-source-image-card
image: |
  media-source://media_source/Immich/USER/HASS_ALBUM/IMG_20250728_180953316_HDR.jpg
```
