### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by Joao-Sousa-71** [luixal/lovelace-media-source-image-card#6]
This is not a issue but a question. Do you plan to include in the future support for video files?
Btw this card is great.

**Comment by luixal** [comment]
Hi,

I've made some test and seems to work fine, although I can only upload really short/small videos due to media source file size limitation (no idea if that's configurable).

Anyhow, I've added support for video in the [latest pre-release](https://github.com/luixal/lovelace-media-source-image-card/releases/tag/v.0.2.2).

Here's an example of how to use and the options available:

```yaml
type: custom:media-source-image-card
image: media-source://media_source/local/shorter.mp4
entity_id: input_boolean.boolean_test
apply_grayscale: true
video_options:
  width: 320
  height: 240
  loop: true
  show_controls: true
  autoplay: true
  muted: false
  type: video/mp4
tap_action:
  action: call-service
  service: input_boolean.turn_on
  target:
    entity_id: input_boolean.boolean_test

```

Can you take it for a ride and give some feedback?

Cheers!
